:construction::umbrella: WIP
heXeo/hbot pull request #14
Opened 2018-07-31 22:45 UTC by OlivierCuyp

Please comment already ...
This should resolve #11

2018-07-31 23:06 UTC, OlivierCuyp commented
I'm still wondering if I should cache the Docker Engine version or not.
And also, this version could differ between nodes.
So depending on which proxy you ask the answer might be different... How do we handle that ?

2018-08-01 06:03 UTC, nekuz0r commented
@OlivierCuyp 

I think we should retrieve the list of all nodes in the swarm cluster, get the version of the docker engine for each of them, then take the lowest one as reference.

It should then cache it for some times before repeating the procedure (on demand).

2018-08-01 10:47 UTC, OlivierCuyp commented
@nekuz0r I'm wondering too where to place the code doing this...
I don't think it really belongs to the DockerApi lib. Maybe more to the Swarm controller since this touch definition and docker api.

2018-08-01 23:35 UTC, OlivierCuyp commented
@nekuz0r could check the new commit. It still missing the cashing but I think this is cleaner...

2018-08-07 11:25 UTC, nekuz0r requested changes

2018-08-07 11:25 UTC, nekuz0r commented on src/controllers/swarm/main.ts
> +  const nodesInfo = await swarmSvc.listNodes()
`const nodes = ...`

2018-08-07 11:25 UTC, nekuz0r commented on src/helpers/composeVersionChecker.ts
> +function cleanEngineVersion(baseEngineVersion: string): string {
Since the compose version of this function is called `normalizeComposeVersion` shouldn't this one called `normalizeEngineVersion` ?

2018-08-07 11:25 UTC, nekuz0r commented on src/helpers/composeVersionChecker.ts
> +function getMinimalEngineVersion(nodesInfo: Array<any>): string {
`nodesInfo` => `nodes`
`nodeInfo` => `node`

2018-08-07 11:25 UTC, nekuz0r commented on src/helpers/composeVersionChecker.ts
> +      lowestEngineVersion = nodeEngineVersion // eslint-disable-line no-param-reassign
No need to reassign, simply return `nodeEngineVersion`, since it inside a reduce, the returned value will automatically be assigned to it.

2018-08-07 11:25 UTC, nekuz0r commented on src/helpers/composeVersionChecker.ts
> +  let calculatedEngineVersion = ''
```
if (!apiVersion) {
  return compareVersions(actualEngineVersion, minimalEngineVersion) >= 0
}

const highestEngineVersion = apiVersionMap[apiVersion]
if (compareVersions(actualEngineVersion, highestEngineVersion) < 0) {
  return actualEngineVersion
}

return highestEngineVersion
```

2018-08-07 11:25 UTC, nekuz0r commented on src/libs/DockerApi.ts
> +  getVersion() {
Make the property `version`public and readonly, thus this getter is not required anymore.
`private version: string` => `public readonly version: string`

2018-08-07 11:25 UTC, nekuz0r commented on src/helpers/composeVersionChecker.ts
> +const composeVersionMap: IVersionMap = {
use a JSON file to store these mappings and enable `resolveJsonModule` typescript option. (may require `esModuleInterop` and/or `allowSyntheticDefaultImports`

2018-08-10 11:07 UTC, nekuz0r approved these changes

2018-08-10 12:00 UTC, merged