:sparkles: add stack deploy prune option
heXeo/hbot pull request #4
Opened 2018-07-10 12:33 UTC by OlivierCuyp

2018-07-11 09:41 UTC, nekuz0r requested changes

2018-07-11 09:41 UTC, nekuz0r commented on src/controllers/swarm/stack.ts
> +export async function deployStack (name: string, prune: false): Promise<string> {
`prune: boolean = false`

2018-07-11 09:41 UTC, nekuz0r commented on src/services/Swarm.ts
> +  async createOrUpdateStack (name: string, apiSpecs: any[], prune = false) {
`prune: boolean = false`

2018-07-11 20:26 UTC, OlivierCuyp commented on src/controllers/swarm/stack.ts
> +export async function deployStack (name: string, prune: false): Promise<string> {
It comes from the doc:

https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters

I don't see this form on the doc, where did you get it ?

2018-07-12 21:52 UTC, nekuz0r approved these changes

2018-07-12 21:52 UTC, merged